project_id = "hr-automate"

[api]
enabled = true
port = 55421
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 2000

[db]
port = 55422
shadow_port = 55420
major_version = 15

[db.pooler]
enabled = false
port = 55429

[studio]
enabled = true
port = 55423

[inbucket]
enabled = false
port = 55424

[storage]
enabled = false

[edge_runtime]
enabled = false
inspector_port = 55428

[analytics]
enabled = false
port = 55427
